// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entities "github.com/totemcaf/k8autotune/app/domain/entities"
import mock "github.com/stretchr/testify/mock"

// ControllerRepository is an autogenerated mock type for the ControllerRepository type
type ControllerRepository struct {
	mock.Mock
}

// FindDeploymentsInNamespace provides a mock function with given fields: namespace
func (_m *ControllerRepository) FindDeploymentsInNamespace(namespace string) []*entities.Controller {
	ret := _m.Called(namespace)

	var r0 []*entities.Controller
	if rf, ok := ret.Get(0).(func(string) []*entities.Controller); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Controller)
		}
	}

	return r0
}

// UpdateResources provides a mock function with given fields: controller
func (_m *ControllerRepository) UpdateResources(controller *entities.Controller) error {
	ret := _m.Called(controller)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Controller) error); ok {
		r0 = rf(controller)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
