// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entities "github.com/totemcaf/k8autotune/app/domain/entities"
import mock "github.com/stretchr/testify/mock"

// MetricsRepository is an autogenerated mock type for the MetricsRepository type
type MetricsRepository struct {
	mock.Mock
}

// CPUUsedForContainer provides a mock function with given fields: container, containerName
func (_m *MetricsRepository) CPUUsedForContainer(container *entities.Controller, containerName string) []int64 {
	ret := _m.Called(container, containerName)

	var r0 []int64
	if rf, ok := ret.Get(0).(func(*entities.Controller, string) []int64); ok {
		r0 = rf(container, containerName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	return r0
}
