// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entities "github.com/totemcaf/k8autotune.git/app/domain/entities"
import mock "github.com/stretchr/testify/mock"

// MetricsRepository is an autogenerated mock type for the MetricsRepository type
type MetricsRepository struct {
	mock.Mock
}

// CPUUsedForPod provides a mock function with given fields: pod
func (_m *MetricsRepository) CPUUsedForPod(pod *entities.Pod) []int {
	ret := _m.Called(pod)

	var r0 []int
	if rf, ok := ret.Get(0).(func(*entities.Pod) []int); ok {
		r0 = rf(pod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	return r0
}
