// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entities "github.com/totemcaf/k8autotune/app/domain/entities"
import mock "github.com/stretchr/testify/mock"

// PodRepository is an autogenerated mock type for the PodRepository type
type PodRepository struct {
	mock.Mock
}

// GetPodsForLabels provides a mock function with given fields: labels
func (_m *PodRepository) GetPodsForLabels(labels map[string]string) []*entities.Pod {
	ret := _m.Called(labels)

	var r0 []*entities.Pod
	if rf, ok := ret.Get(0).(func(map[string]string) []*entities.Pod); ok {
		r0 = rf(labels)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Pod)
		}
	}

	return r0
}
